### ISSUE TITLE
Can't find module 'underscore.string' in config.coffee

### ISSUE THREAD

**Issue by ssfinney** [dpen2000/Codecombat-Vagrant#14]
Running ```brunch watch``` causes an error when loading ```config.coffee``` inside the /coco directory.

Originally, it couldn't find lodash, so I installed it globally with ```npm install -g lodash```. That fixed that problem, but now it can't find underscore, even though I globally installed it too.

The problem originates from this line from config.coffee: ```_.str = require 'underscore.string'```. I'm reading up about setting the NODE_PATH environment variable, but with no success so far.

Any thoughts? The stack trace is below. I'm running Mac OS X, v. 10.10.1.

```
Error: couldn't load config /coco/config.coffee. Error: Cannot find module 'underscore.string'
  at Object.exports.loadConfig (/home/vagrant/.nvm/v0.10.35/lib/node_modules/brunch/lib/helpers.js:514:15)
  at Object.exports.loadConfig (/home/vagrant/.nvm/v0.10.35/lib/node_modules/brunch/lib/helpers.js:512:24)
  at initialize (/home/vagrant/.nvm/v0.10.35/lib/node_modules/brunch/lib/watch.js:453:20)
  at new BrunchWatcher (/home/vagrant/.nvm/v0.10.35/lib/node_modules/brunch/lib/watch.js:607:7)
  at module.exports.watch (/home/vagrant/.nvm/v0.10.35/lib/node_modules/brunch/lib/watch.js:663:12)
  at start (/home/vagrant/.nvm/v0.10.35/lib/node_modules/brunch/lib/index.js:13:33)
  at Command.<anonymous> (/home/vagrant/.nvm/v0.10.35/lib/node_modules/brunch/node_modules/commander/index.js:249:8)
  at Command.emit (events.js:98:17)
  at Command.parseArgs (/home/vagrant/.nvm/v0.10.35/lib/node_modules/brunch/node_modules/commander/index.js:472:12)
  at Command.parse (/home/vagrant/.nvm/v0.10.35/lib/node_modules/brunch/node_modules/commander/index.js:370:21)
  at Object.exports.run (/home/vagrant/.nvm/v0.10.35/lib/node_modules/brunch/lib/cli.js:49:13)
  at Object.<anonymous> (/home/vagrant/.nvm/v0.10.35/lib/node_modules/brunch/bin/brunch:11:22)
  at Module._compile (module.js:456:26)
  at Object.Module._extensions..js (module.js:474:10)
  at Module.load (module.js:356:32)
  at Function.Module._load (module.js:312:12)
  at Function.Module.runMain (module.js:497:10)
  at startup (node.js:119:16)
  at node.js:929:3
```

**Comment by dpen2000** [comment]
Sorry. Been super busy. I'm going to see what happens for me now.

**Comment by ssfinney** [comment]
@dpen2000 Any update on this? Is there anything I can do to help?

**Comment by dpen2000** [comment]
Hi @ssfinney, Sorry it's taken so long to get back to you. I've just run through the instructions in the readme with the latest codecombat code and this still works for me (right through to playing a level). Are you following the readme? For instance, I don't have /home/vagrant/.nvm created after running through those instructions.

**Comment by ssfinney** [comment]
Hey @dpen2000, no problem! Thanks for replying.

I just tried again, following the readme, with the same result (without the .nvm directory, however).

I'm using VMware fusion, would that cause a problem? Do I have to run this with Virtualbox?

```
Error: couldn't load config /coco/config.coffee. Error: Cannot find module 'lodash'
  at Object.exports.loadConfig (/usr/lib/node_modules/brunch/lib/helpers.js:514:15)
  at Object.exports.loadConfig (/usr/lib/node_modules/brunch/lib/helpers.js:512:24)
  at initialize (/usr/lib/node_modules/brunch/lib/watch.js:453:20)
  at new BrunchWatcher (/usr/lib/node_modules/brunch/lib/watch.js:607:7)
  at module.exports.watch (/usr/lib/node_modules/brunch/lib/watch.js:663:12)
  at start (/usr/lib/node_modules/brunch/lib/index.js:13:33)
  at Command.<anonymous> (/usr/lib/node_modules/brunch/node_modules/commander/index.js:249:8)
  at Command.emit (events.js:98:17)
  at Command.parseArgs (/usr/lib/node_modules/brunch/node_modules/commander/index.js:472:12)
  at Command.parse (/usr/lib/node_modules/brunch/node_modules/commander/index.js:370:21)
  at Object.exports.run (/usr/lib/node_modules/brunch/lib/cli.js:49:13)
  at Object.<anonymous> (/usr/lib/node_modules/brunch/bin/brunch:11:22)
  at Module._compile (module.js:456:26)
  at Object.Module._extensions..js (module.js:474:10)
  at Module.load (module.js:356:32)
  at Function.Module._load (module.js:312:12)
  at Function.Module.runMain (module.js:497:10)
  at startup (node.js:119:16)
  at node.js:906:3
```

**Comment by dpen2000** [comment]
Hi @ssfinney, I'm really sorry: I don't really have the time/headspace to support codecombat-vagrant at the moment. It has worked fairly well for me in the past - sometimes something has gone wrong but it's normally fixed itself if I destroy the vm and rebuild it. I have been trying to slot in an hour or so here and there to look at this but it's not really working. I'd suggest seeing if the guys at Codecombat can take a fork of this repository and have a play with it. Again, apologies.

**Comment by ssfinney** [comment]
@dpen2000 That's OK, I haven't had much time either! I'll look at this more sometime when I get a second.

**Comment by bambii7** [comment]
I think this might be an issue with npm underscore.string I get the same issue after a fresh install of my sailsjs project.

git clone
npm install
node app.js
Error: Cannot find module 'underscore.string'

 On Ubuntu 14.04, node v0.12.7, npm 2.11.3

**Comment by dpen2000** [comment]
Please see how to use updated version of this here: https://github.com/codecombat/codecombat/wiki/Dev-Setup:-Vagrant and direct any queries to main codecombat repository. Thanks.

**Comment by ssfinney** [comment]
Thanks for the update
